name: Build Flipper Zero App

on:
  push:
    branches:
      - main  # Sostituisci con il nome del tuo branch (es. master, dev)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Versione aggiornata

      - name: Set up Python
        uses: actions/setup-python@v5  # Versione aggiornata
        with:
          python-version: '3.11'  # Usa Python 3.11 o superiore

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang cmake libusb-1.0-0-dev

      - name: Build application
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Versione corretta
        with:
          name: flipper-app
          path: build/*.fap  # Verifica il percorso del file .fap
